# Generated by Django 5.1.7 on 2025-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpromo',
            old_name='product_inventory_id',
            new_name='product_inventory',
        ),
        migrations.RenameField(
            model_name='productpromo',
            old_name='promotion_id',
            new_name='promotion',
        ),
        migrations.AddField(
            model_name='productpromo',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpromo',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productpromo',
            unique_together={('product_inventory', 'promotion')},
        ),
    ]
