# Generated by Django 5.1.7 on 2025-03-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['created_at']},
        ),
    ]
