# Generated by Django 5.1.7 on 2025-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='img_url',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='products/images/placeholder.jpg', upload_to='products/images/'),
        ),
    ]
