# Generated by Django 5.1.7 on 2025-03-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_product'),
        ('products', '0005_remove_productattribute_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_set', to='products.product'),
        ),
    ]
