# Generated by Django 5.1.7 on 2025-03-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattribute_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.producttype'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute'),
        ),
    ]
